import { InitializationSpec } from '../core/types.js'

export function codingRuleFiles(spec: InitializationSpec): Array<[string, string]> {
  return [
    ['.coding-rules/style.md', `# Style Rules

- Keep modules cohesive and small.
- Prefer clear TypeScript types over implicit object shapes.
- Avoid unrelated refactors during focused changes.
`],
    ['.coding-rules/architecture.md', `# Architecture Rules

- Hard skeleton is deterministic.
- Soft documentation content may be generated by AI.
- Git hooks call quick-init commands instead of embedding business logic.
`],
    ['.coding-rules/testing.md', `# Testing Rules

- Add focused Vitest coverage for every behavior change.
- Use temporary Git repositories for Git behavior tests.
- Verify staged file behavior with real git commands.
`],
    ['.coding-rules/security.md', `# Security Rules

- Do not commit local .quick-init runtime state.
- Do not leak model credentials in generated docs or manifests.
`],
    ['.coding-rules/git-workflow.md', `# Git Workflow Rules

- Use scoped staging only.
- Never use git add -A in quick-init automation.
- Preserve unrelated dirty work.
`],
    ['.coding-rules/documentation.md', `# Documentation Rules

- Markdown submitted with a commit may be classified and archived.
- If classification is uncertain, use summarize-only.
- Manifest files are the machine-readable facts.
`]
  ]
}
